titel: "Regulative BeHANDlung"
meta_description: "Regulative BeHANDlung – Heilpraktikerin Martina Stöcker"
logo: "/img/logo-mini.png"
logo_alt: "Regulative BeHANDlung Logo"
hero_foto: "/img/martina.jpg"
hero_foto_alt: "Martina Stöcker – Heilpraktikerin"
hero_logo: "/img/logo_no_adress_new-e1585121979333.png"
hero_logo_alt: "Martina Stöcker – Heilpraktikerin – Regulative BeHANDlung"
hero_overlay_titel: "ICH BIN …"
hero_overlay_text: |
  Jahrgang 1964, seit 1986 verheiratet, Mutter von zwei Söhnen,
  Schwiegermutter und Oma 😍, Zahnarzthelferin, Heilpraktikerin,
  AKUPUNKT-MASSAGE Therapeutin, Ortho-Bionomy-Praktioner,
  THEKI BewusstseinsTrainer, selbständig, in eigener Praxis,
  seit 1997
hero_overlay_schluss: "… die ICH BIN"
footer_copyright: "Copyright 2025 – by Martina Stöcker"
